### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by ib**
No other option ends with a period.

(See OptFilterXGet, ShowFullAddresses or KeepLocked for examples of options with additional explanations.)

### CODE REVIEW

**Comment by ib** [comment]
Added translation for the "csspp0" capability.

**Comment by ib** [comment]
Please consider.

**Comment by ib** [comment]
"unbeschränkt" sounds strange, "uneingeschränkt" would be better, but even longer, my suggestion is to allow _all CSS_ to make it short. (I tried to join OTF's localization lab, but got no answer, although being an active translator.)

**Comment by ib** [comment]
@musonius

Referring to the [forum discussion](https://forums.informaction.com/viewtopic.php?f=7&t=26335&p=104049#p104049):

> I don't think that the translation "alles CSS" is correct because it does not communicate anything close to "unrestricted CSS" or "unchecked CSS" and it sounds super weird. This should read "unbeschränktes CSS" (which means exactly "unrestricted CSS")

I disagree.

First of all it should read "uneingeschränktes CSS" rather that "unbeschränktes CSS", because CSS isn't "beschränkt" but "eingeschränkt".

Also, "unrestricted CSS" or "unchecked CSS" doesn't communicate anything either, because a normal user doesn't know why and how CSS is restricted or checked.

Since all the allowances/capabilities consist of only one word, the idea was to concisely communicate "allow any CSS, without checks from NoScript".

I agree that "alles CSS" probably sounds weird.

What about "jedes CSS", i.e. short for "allow: any Cascading Style Sheet(s)"? (I think in German CSS is commonly also used in the singular.)

@hackademix 

What do you think of "any CSS" instead of "unrestricted CSS" as English term?

The fact that there is a check or restriction is a programmer's view. The user is more interested in what they ultimately allow. (Just my opinion though.)

**Comment by musonius** [comment]
CSS can be singular, if just one particular stylesheet is meant, or plural otherwise. In this case "alle CSS" is correct, but I don't think "alles CSS". This is something different to "Alles Glück der Erde". If you want to use CSS in singular, you better write "jedes CSS" indeed.

The words "uneingeschränkt and "unbeschränkt" are synonyms (also according to the Duden).

The developer's stated intention is to preserve the meaning of "unrestricted" or "unchecked" in translation. This and the weirdness of "alles CSS" were the reasons for reverting the change.

If script is unchecked, each script is supposed to be blocked (and vice versa). CSS is different to the other content types, because unchecked does not mean that a content type is to be blocked, but that an algorithm checks which CSS are to be allowed and which are to be blocked. It is intransparent to the users, which CSS are supposed to be blocked.

**Pull request merged**
