### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by ib**
Throughout NoScript we don't talk about "blockierte Fähigkeiten" but about "Einschränkungen".

Also, fix indentation.

### CODE REVIEW

**Comment by musonius** [comment]
The suggested change reflects the original version of that option which was changed because [it was not understood by many users](https://forums.informaction.com/viewtopic.php?f=7&t=25593#p100955). There have been several support requests in the forum about that.

The original text: Cascade top document's restrictions to subdocuments
The current text: Any capability blocked in the top document must be blocked in its subdocuments too

It is true, that "Fähigkeiten" is unique, but so is "capability". I am not fully satisfied with "Fähigkeiten", though.

By the way, in my opinion the suggested translation should better read "Einschränkungen des obersten Dokuments auch auf seine Unterdokumente anwenden". Since this change has already found its way to Transifex, I have corrected the translation accordingly.

[Link to the forum discussion](https://forums.informaction.com/viewtopic.php?f=7&t=26335&p=104049#p104049).

**Comment by musonius** [comment]
Personally, I understand what the option does. However, the new text leaves open, if the restrictions of the top document are being applied in addition of the restrictions of subdocuments or if they replace them whatever they are. The text "Any capability blocked in the top document must be blocked in its subdocuments too" is clearer in that regard.

**Comment by ib** [comment]
@musonius 

> By the way, in my opinion the suggested translation should better read "Einschränkungen des obersten Dokuments auch auf seine Unterdokumente anwenden".

I agree, but what would a non-expert user conceive of "_oberstes_ Dokument"? In my opinion, "Hauptdokument" is a more understandable.

> The text "Any capability blocked in the top document must be blocked in its subdocuments too" is clearer in that regard.

That should translate "Alle nicht zugelassenen Berechtigungen im Hauptdokument auch in seinen Unterdokumenten nicht zulassen" then, because we speak of "zulassen" and "Berechtigungen" everywhere else.

**Comment by musonius** [comment]
> In my opinion, "Hauptdokument" is a more understandable.

I think you are right that "Hauptdokument" is better indeed and should be used elsewhere as well.

> That should translate "Alle nicht zugelassenen Berechtigungen im Hauptdokument auch in seinen Unterdokumenten nicht zulassen" then, because we speak of "zulassen" and "Berechtigungen" everywhere else.

Consistency is important, but "capability" cannot be found elsewhere either. That being said, I have not been happy with the former German translation and therefore I fully agree that it should be improved.

Another idea: "Anything not allowed in the top document must also be blocked in its subdocuments" (German: "Alles im Hauptdokument nicht Erlaubte muss auch in seinen Unterdokumenten blockiert werden")

**Comment by musonius** [comment]
OK. I have changed the translation of "top document" to "Hauptdokument" (2 messages).

The message we are discussing here reads as suggested in my previous comment now.

**Comment by ib** [comment]
@musonius 

> The message we are discussing here reads as suggested in my previous comment now.

Sorry, but that is awful and it literally translates "blocked" again.

Your first (and edited) idea, however, was **by far** better: "In Unterdokumenten nichts erlauben, was nicht auch im Hauptdokument erlaubt ist". (Even better after replacing "erlauben" with "zulassen" to refer to "Zulassen" in the preset customization.) This translation is concise, straightforward and easy to understand.

**Comment by hackademix** [comment]
> OK. I have changed the translation of "top document" to "Hauptdokument" (2 messages).
> 
> The message we are discussing here reads as suggested in my previous comment now.

I'm very happy of the discussion and collaboration that is happening here (even more because regrettably I don't understand a word of German, except "Also sprach Zarathustra", "Mein Kampf" and "Kartoffel").

Question for @musonius  : when you say "I have changed", where do you mean? In another PR? On Transifex? 

To both, is either of you a registered volunteer translator on the OTF Localization Lab Transifex instance?
When you reach an agreement on the best translation, will I see it reflected on Transifex (where I pull my translation from before stable releases) or should I merge some PR of yours (like this one) instead?

Thanks!

**Comment by ib** [comment]
@hackademix 

> To both, is either of you a registered volunteer translator on the OTF Localization Lab Transifex instance?

Both of us. Translation is on Transifex and I will close this pull request then.

**Comment by musonius** [comment]
> when you say "I have changed", where do you mean? In another PR? On Transifex?

@hackademix : Transifex.

> Your first (and edited) idea, however, was by far better: "In Unterdokumenten nichts erlauben, was nicht auch im Hauptdokument erlaubt ist". (Even better after replacing "erlauben" with "zulassen" to refer to "Zulassen" in the preset customization.) This translation is concise, straightforward and easy to understand.

That is: **In Unterdokumenten nichts zulassen, was nicht auch im Hauptdokument zugelassen ist**

Now, after a night's sleep, this earlier version (including your suggestion) also seems much better to me than the last version, and I can't explain why I dropped it yesterday.

I don't want the latest change to end up in NoScript (whether rc or release), so I've updated the message at Transifex again. But that doesn't mean it can't be improved further, if you come up with even better suggestions.

By the way, I was not aware that you are also a volunteer translator at Transifex. I had difficulties with this particular message and it is good to discuss the translation constructively to come to a good and understandable result.

**Comment by ib** [comment]
@musonius 

> But that doesn't mean it can't be improved further, if you come up with even better suggestions.

After a night's sleep, I think the cascading effect is better described by simply swapping the main and subordinate clauses: "Alles, was im Hauptdokument nicht zugelassen ist, auch in seinen Unterdokumenten nicht zulassen".

**Comment by musonius** [comment]
> Alles, was im Hauptdokument nicht zugelassen ist, auch in seinen Unterdokumenten nicht zulassen

I think you are right and we are done (unless you find an even better translation, because I don't think I can further improve it). Therefore, I have changed the translation at Transifex again. Thanks for the constructive discussion!

**Pull request closed without merging**
